import java.util.Random;

public class NameGenerator {

    private static String[] FirstName = {
            "James", "Mary",
            "John", "Patricia",
            "Robert", "Jennifer",
            "Michael", "Linda",
            "William", "Elizabeth",
            "David", "Barbara",
            "Richard", "Susan",
            "Joseph	", "Jessica",
            "Thomas	", "Sarah",
            "Charles", "Karen",
            "Christopher", "Nancy",
            "Daniel", "Lisa",
            "Matthew", "Margaret",
            "Anthony", "Betty",
            "Donald	", "Sandra",
            "Mark	", "Ashley",
            "Paul	", "Dorothy",
            "Steven	", "Kimberl",
            "Andrew	", "Emily",
            "Kenneth", "Donna",
            "Joshua	", "Michell",
            "Kevin	", "Carol",
            "Brian	", "Amanda",
            "George	", "Melissa",
            "Edward	", "Deborah",
            "Ronald	", "Stephanie",
            "Timothy", "Rebecca",
            "Jason	", "Laura",
            "Jeffrey", "Sharon",
            "Ryan", "Cynthia",
            "Jacob", "Kathleen",
            "Gary", "Amy",
            "Nicholas", "Shirley",
            "Eric", "Angela",
            "Jonathan", "Helen",
            "Stephen", "Anna",
            "Larry", "Brenda",
            "Justin", "Pamela",
            "Scott", "Nicole",
            "Brandon", "Samantha",
            "Benjamin", "Katherine",
            "Samuel	,	Emma",
            "Frank", "Ruth",
            "Gregory", "Christine",
            "Raymond", "Catherine",
            "Alexander", "Debra",
            "Patrick", "Rachel",
            "Jack", "Carolyn",
            "Dennis", "Janet",
            "Jerry", "Virginia",
            "Tyler", "Maria",
            "Aaron", "Heather",
            "Jose", "Diane",
            "Henry", "Julie",
            "Adam", "Joyce",
            "Douglas", "Victoria",
            "Nathan", "Kelly",
            "Peter", "Christina",
            "Zachary", "Lauren",
            "Kyle", "Joan",
            "Walter", "Evelyn",
            "Harold", "Olivia",
            "Jeremy", "Judith",
            "Ethan", "Megan",
            "Carl", "Cheryl",
            "Keith", "Martha",
            "Roger", "Andrea",
            "Gerald", "Frances",
            "Christian", "Hannah",
            "Terry", "Jacqueline",
            "Sean", "Ann",
            "Arthur", "Gloria",
            "Austin", "Jean",
            "Noah", "Kathryn",
            "Lawrence", "Alice",
            "Jesse", "Teresa",
            "Joe", "Sara",
            "Bryan", "Janice",
            "Billy", "Doris",
            "Jordan", "Madison",
            "Albert", "Julia",
            "Dylan", "Grace",
            "Bruce", "Judy",
            "Willie", "Abigail",
            "Gabrie", "Marie",
            "Alan", "Denise",
            "Juan", "Beverly",
            "Logan", "Amber",
            "Wayne", "Theresa",
            "Ralph", "Marilyn",
            "Roy", "Danielle",
            "Eugene", "Diana",
            "Randy", "Brittany",
            "Vincent", "Natalie",
            "Russell", "Sophia",
            "Louis", "Rose",
            "Philip", "Isabella",
            "Bobby", "Alexis",
            "Johnny", "Kayla",
            "Bradley"};
    private static String[] FamilyName = {
            "Smith",
            "Johnson",
            "Williams",
            "Brown",
            "English",
            "Garcia",
            "Miller",
            "Davis",
            "Rodriguez",
            "Martinez",
            "Hernandez",
            "Lopez",
            "Gonzales",
            "Wilson",
            "Anderson",
            "Thomas",
            "Taylor",
            "Moore",
            "English",
            "Jackson",
            "Martin",
            "Perez",
            "Thompson",
            "Harris",
            "Sanchez",
            "Clark",
            "Ramirez",
            "Lewis",
            "Robinson",
            "Walker",
            "Young",
            "Allen",
            "King",
            "Wright",
            "Scott",
            "Torres",
            "Nguyen",
            "Hill",
            "Flores",
            "Green",
            "Adams",
            "Nelson",
            "Baker",
            "Hall",
            "Rivera",
            "Campbell",
            "Mitchell",
            "Carter",
            "Roberts",
            "Gomez",
            "Phillips",
            "Evans",
            "Turner",
            "Diaz",
            "Parker",
            "Cruz",
            "Edwards",
            "Collins",
            "Reyes",
            "Stewart",
            "Morris",
            "Morales",
            "Murphy",
            "Cook",
            "Rogers",
            "Gutierrez",
            "Ortiz",
            "Morgan",
            "Cooper",
            "Peterson",
            "Bailey",
            "Reed",
            "Kelly",
            "Howard",
            "Ramos",
            "Kim",
            "Cox",
            "Ward",
            "Richardson",
            "Watson",
            "Brooks",
            "Chavez",
            "Wood",
            "James",
            "Bennet",
            "Gray",
            "Mendoza",
            "Ruiz",
            "Hughes",
            "Price",
            "Alvarez",
            "Castillo",
            "Sanders",
            "Patel",
            "Myers",
            "Ross",
            "Foster",
            "Jimenez",
    };

    private static Random random = new Random();

    public String generateFirstName() {
        return FirstName[random.nextInt(FirstName.length)];
    }

    public String generateFamilyName() {
        return FamilyName[random.nextInt(FamilyName.length)];
    }
}

